spring.application.name=backend

# Base de datos
#PRODCUCION
#spring.datasource.url= jdbc:postgresql://localhost:5432/sprint_manager_producion
#DEV
spring.datasource.url=jdbc:postgresql://localhost:5432/sprint_manager_dev
spring.datasource.username=postgres
spring.datasource.password=4448
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto (opcional, pero explícito)
server.port=8080